name: custom_clipboard_example
description: Demonstrates how to use the custom_clipboard plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.7'

dependencies:
  custom_clipboard:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
