name: custom_clipboard_example
description: Demonstrates how to use the custom_clipboard plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  custom_clipboard:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
