name: custom_clipboard_platform_interface
description: A common platform interface for the custom_clipboard plugin.
version: 0.0.2
repository:  https://github.com/thorito/custom_clipboard.git
issue_tracker:  https://github.com/thorito/custom_clipboard/issues?q=is%3Aissue+is%3Aopen

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.7'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.3.0
